# -------------------------------------------------------------------
# General mandatory settings
# -------------------------------------------------------------------
packageName: sense-media-box

# -------------------------------------------------------------------
# Task specific settings
# -------------------------------------------------------------------

wbfolder:
  enabled: false

# -------------------------------------------------------------------
# Deployment
# -------------------------------------------------------------------
deployment:
  toLocal:
    enabled: false
    pathFetching: true              # By default the path will be automatically fetched.
    extensionBaseDir: null          # Define the extensionBaseDir if pathFetching is disabled and you still want to deploy locally
  qrs:                              # Not implemented, yet
    enabled: false
    url: null
